### ISSUE TITLE
Persist data in hard disk

### ISSUE THREAD

**Issue by atellezr** [sciensa/node-red-contrib-lokijs#3]
Hi,

I've just checked this library and I found it interesting and quite suitable for me, but I need to persist the data and I've seen this:

_The INSERT method only works in-memory and does NOT save to file. The filename is currently only used to instantiate the DB class._

I've just done a small test locally modifying the file _lokijs.js_ in order to add the possibility to persist the data:

```
function init(config) {
  const lokidb = new Loki(config.filename, {autoload: true, autosave: true, autosaveInterval: 4000});
...
```
(source: https://rawgit.com/techfort/LokiJS/master/jsdoc/tutorial-Persistence%20Adapters.html)

And it stores the data in the file, and apparently everything working fine
Is there a reason that I haven't found yet to not offer this possibility? Do you have in mind to add it?

Thanks!
Regards

**Comment by machad0** [comment]
Hey, thanks for your contribution. Could you add the instructions of your changes at `README.md`, like where and how to change `settings.js` file if someone's wishes to persist data in disk.

cheers

**Comment by atellezr** [comment]
Hi,

I've added it and created a new pull request

Thanks!!

**Comment by machad0** [comment]
Awesome!
